import jsPDF from 'jspdf'
import { modules, calculatePrice } from '@mig/modules-schema'
import type { ModuleInstance } from '@/stores/configurator'

const USD_RATE = 0.37

export type CostMultipliers = {
  materialPremium: number   // 0..1 (premium added on top)
  locationMultiplier: number // 1..2
  rushMultiplier: number     // 1..2
}

// English-only labels: jsPDF default helvetica can't render Cyrillic without addFont.
export function generateBomPdf(
  instances: ModuleInstance[],
  cost: CostMultipliers,
): void {
  if (instances.length === 0) return

  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const M = 40
  let y = M

  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('MIG Constructor', M, y)
  y += 22
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text('Bill of Materials', M, y)
  y += 14
  doc.setFontSize(9)
  doc.setTextColor(120)
  doc.text(new Date().toISOString().slice(0, 10), M, y)
  doc.setTextColor(0)
  y += 24

  // Header
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('#', M, y)
  doc.text('Module', M + 24, y)
  doc.text('Material', M + 180, y)
  doc.text('Area m2', M + 260, y)
  doc.text('USD', W - M - 60, y, { align: 'right' })
  y += 4
  doc.setDrawColor(180)
  doc.line(M, y, W - M, y)
  y += 12
  doc.setFont('helvetica', 'normal')

  // Rows
  let subtotal = 0
  let totalArea = 0
  instances.forEach((inst, i) => {
    const m = modules.find((x) => x.id === inst.moduleId)
    if (!m) return
    const priceGel = m.price_usd[inst.material as 'container' | 'timber' | 'hybrid'] ?? 0
    const priceUsd = priceGel ?? 0
    subtotal += priceUsd
    totalArea += m.area_m2
    if (y > 760) {
      doc.addPage()
      y = M
    }
    doc.text(String(i + 1), M, y)
    doc.text(m.name.en, M + 24, y)
    doc.text(inst.material, M + 180, y)
    doc.text(m.area_m2.toString(), M + 260, y)
    doc.text(priceUsd.toLocaleString(), W - M - 60, y, { align: 'right' })
    y += 14
  })

  // Totals & cost adjustments
  y += 8
  doc.setDrawColor(0)
  doc.line(M, y, W - M, y)
  y += 16
  doc.setFont('helvetica', 'bold')
  doc.text(`Modules subtotal:`, M, y)
  doc.text(`USD ${subtotal.toLocaleString()}`, W - M, y, { align: 'right' })
  y += 14

  const base = calculatePrice(instances.map((i) => ({ moduleId: i.moduleId, material: i.material })))
  const baseUsd = base.total * USD_RATE
  const premium = baseUsd * cost.materialPremium
  const locAdj = baseUsd * (cost.locationMultiplier - 1)
  const rushAdj = baseUsd * (cost.rushMultiplier - 1)
  const finalUsd = Math.round(baseUsd + premium + locAdj + rushAdj)

  doc.setFont('helvetica', 'normal')
  doc.text(`Total area:`, M, y); doc.text(`${totalArea.toFixed(1)} m2`, W - M, y, { align: 'right' }); y += 12
  doc.text(`Delivery + earthworks + assembly:`, M, y); doc.text(`USD ${Math.round(baseUsd - subtotal).toLocaleString()}`, W - M, y, { align: 'right' }); y += 12
  doc.text(`Material premium (+${Math.round(cost.materialPremium * 100)}%):`, M, y); doc.text(`USD ${Math.round(premium).toLocaleString()}`, W - M, y, { align: 'right' }); y += 12
  doc.text(`Site difficulty (x${cost.locationMultiplier.toFixed(2)}):`, M, y); doc.text(`USD ${Math.round(locAdj).toLocaleString()}`, W - M, y, { align: 'right' }); y += 12
  doc.text(`Rush factor (x${cost.rushMultiplier.toFixed(2)}):`, M, y); doc.text(`USD ${Math.round(rushAdj).toLocaleString()}`, W - M, y, { align: 'right' }); y += 16

  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text(`FINAL TOTAL:`, M, y)
  doc.text(`USD ${finalUsd.toLocaleString()}`, W - M, y, { align: 'right' })
  y += 24

  doc.setFontSize(8)
  doc.setTextColor(140)
  doc.setFont('helvetica', 'normal')
  doc.text('Generated by MIG Constructor · mig-constructor.app', M, 820)

  doc.save(`mig-bom-${Date.now()}.pdf`)
}
