import jsPDF from 'jspdf'
import { modules as moduleCatalog } from '@mig/modules-schema'
import type { ModuleInstance } from '@/stores/configurator'

export type BomOptions = {
  projectName?: string
  materialPremium: number
  locationMultiplier: number
  rushMultiplier: number
}

const DELIVERY_USD = 1500
const EARTHWORKS_USD = 3000
const ASSEMBLY_PER_MODULE_USD = 800

export function generateBomPdf(instances: ModuleInstance[], opts: BomOptions): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  doc.setFillColor(10, 10, 11)
  doc.rect(0, 0, 210, 35, 'F')
  doc.setTextColor(0, 210, 106)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.text('MIG Constructor', 20, 18)
  doc.setTextColor(245, 245, 247)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text('Bill of Materials / Specification', 20, 26)

  doc.setTextColor(20, 20, 20)
  doc.setFontSize(10)
  const project = opts.projectName ?? 'Untitled Project'
  doc.text(`Project: ${project}`, 20, 45)
  doc.text(`Generated: ${new Date().toLocaleDateString('en-GB')}`, 20, 51)
  doc.text(`Modules: ${instances.length}`, 20, 57)

  let y = 72
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('Module', 20, y)
  doc.text('Material', 90, y)
  doc.text('Area m2', 130, y)
  doc.text('Price USD', 165, y)
  y += 3
  doc.setDrawColor(0, 210, 106)
  doc.line(20, y, 190, y)
  y += 7

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  let subtotal = 0
  let totalArea = 0

  for (const inst of instances) {
    const meta = moduleCatalog.find((m) => m.id === inst.moduleId)
    if (!meta) continue
    const price = (meta.price_usd as Record<string, number | null>)[inst.material] ?? 0
    subtotal += price
    totalArea += meta.area_m2

    doc.text(meta.name.en, 20, y)
    doc.text(inst.material, 90, y)
    doc.text(String(meta.area_m2), 130, y)
    doc.text(`$${price.toLocaleString('en-US')}`, 165, y)
    y += 6
    if (y > 260) { doc.addPage(); y = 25 }
  }

  y += 4
  doc.setDrawColor(150, 150, 150)
  doc.line(20, y, 190, y)
  y += 8

  const premiumed = subtotal * (1 + opts.materialPremium)
  const located = premiumed * opts.locationMultiplier
  const delivery = DELIVERY_USD * opts.locationMultiplier
  const earthworks = EARTHWORKS_USD * opts.locationMultiplier
  const assembly = ASSEMBLY_PER_MODULE_USD * instances.length * opts.rushMultiplier
  const grand = located + delivery + earthworks + assembly

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  const rows: Array<[string, number]> = [
    ['Modules subtotal', subtotal],
    ['Material premium', premiumed - subtotal],
    ['Location multiplier', located - premiumed],
    ['Delivery', delivery],
    ['Earthworks + foundation', earthworks],
    ['Assembly (rush adjusted)', assembly],
  ]
  for (const [label, val] of rows) {
    doc.text(label, 90, y)
    doc.text(`$${Math.round(val).toLocaleString('en-US')}`, 165, y)
    y += 6
  }

  y += 2
  doc.setDrawColor(0, 210, 106)
  doc.setLineWidth(0.6)
  doc.line(90, y, 190, y)
  y += 8
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text('TOTAL', 90, y)
  doc.text(`$${Math.round(grand).toLocaleString('en-US')}`, 165, y)
  y += 10
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  doc.text(`Total floor area: ${totalArea} m2`, 90, y)
  y += 5
  doc.text('Prices indicative. Final quote subject to site survey.', 20, y)

  doc.setFontSize(8)
  doc.text('Generated by MIG Constructor v0.6 | mig-constructor', 20, 285)

  doc.save(`mig-bom-${Date.now()}.pdf`)
}
